version: '3.8'

services:
  mongodb: 
    image: mongo
    container_name: mongodb
    ports: 
      - "27017:27017"
    volumes: 
      - volume_mongo:/data/db
  backend1: 
    image: backend1
    container_name: backend_app
    depends_on:
      - mongodb
    ports: 
      - "3000:3000"
    environment: 
      MONGO_URL: "mongodb://mongodb:27017"

volumes: 
  volume_mongo:
